server:
  port: 8081
spring:
  application:
    name: msvc-usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/d_k
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect